const projects = {
    eng: [{
            "name": "Tomorrow is Nearly Yesterday",
            "description": "Custom-designed skin for Foroactivo.com immerses users in a sci-fi, time-travel-themed roleplay environment. Crafted entirely with HTML, CSS, and JavaScript.",
            "link": "https://tiny-rpg.foroactivo.com",
            "img": "assets/tiny.png",
            "kind": "big",
        },
        {
            "name": "Custom Business Website",
            "description": "A sleek, responsive website designed for a fictional coffeeshop. Built with Tailwind CSS and ReactJS to showcase modern design principles, reusable components, and client-first thinking.",
            "link": "https://ink-and-ember.vercel.app/",
            "img": "assets/inkandember.png",
            "kind": "big",
        },
        {
            "name": "Fairy Adventure",
            "description": "Developed as the final project for CS1420 at the University of Utah. Players strategically place towers to prevent enemies from reaching their destination. The game features multiple levels, tower upgrades, and enemy waves. Created with Java.",
            "link": "/project2.html",
            "img": "assets/towerdefense.png",
            "kind": "",
        },
        {
            "name": "Camp Half-Blood Quiz",
            "description": "Personality-style quiz inspired by the Percy Jackson series. Users answer 20 everyday scenario questions to discover their Greek god parent. Built with React and Tailwind CSS, featuring dynamic scoring and responsive design.",
            "link": "https://quizcamphalfblood.vercel.app/",
            "img": "assets/camphalfblood.png",
            "kind": "",
        },
        // {
        //     "name": "Project 5",
        //     "description": "the fifth heheh",
        //     "link": "/project5.html",
        //     "img": "https://placehold.co/600x400/83c412/31343C",
        //     "kind": "",
        // },
        // {
        //     "name": "Project 6",
        //     "description": "this is the sixth!!",
        //     "link": "/project6.html",
        //     "img": "https://placehold.co/600x400/123456/31343C",
        //     "kind": "",
        // },
    ],

    spa: [{
            "name": "Tomorrow is Nearly Yesterday",
            "description": "Este tema personalizado para Foroactivo.com sumerge a los usuarios en un entorno de rol temático de ciencia ficción y viajes en el tiempo. Creada completamente con HTML, CSS y JavaScript.",
            "link": "https://tiny-rpg.foroactivo.com",
            "img": "assets/tiny.png",
            "kind": "big",
        },
        {
            "name": "Custom Business Website",
            "description": "Un tema moderno y responsivo diseñado para una cafetería ficticia. Desarrollado con ReactJS y Tailwind CSS para destacar principios de diseño contemporáneo, componentes reutilizables y enfoque centrado en el cliente.",
            "link": "https://ink-and-ember.vercel.app/",
            "img": "assets/inkandember.png",
            "kind": "big",
        },
        {
            "name": "Fairy Adventure",
            "description": "Desarrollado como proyecto final para el curso CS1420 en la Universidad de Utah. Los jugadores deben colocar estratégicamente torres para evitar que los enemigos lleguen a su destino. El juego incluye múltiples niveles, mejoras de torres y oleadas de enemigos. Creado con Java.",
            "link": "/project2.html",
            "img": "assets/towerdefense.png",
            "kind": "",

        },
        {
            "name": "Camp Half-Blood Quiz",
            "description": "Un quiz de personalidad inspirado en la serie Percy Jackson. Los usuarios responden 20 preguntas sobre situaciones cotidianas para descubrir quién sería su padre o madre del Olimpo. Construido con React y Tailwind CSS, con lógica dinámica y diseño responsivo.",
            "link": "https://quizcamphalfblood.vercel.app/",
            "img": "assets/camphalfblood.png",
            "kind": "",
        },
        // {
        //     "name": "Proyecto 3",
        //     "description": "Para mi tercer proyecto",
        //     "link": "/project1.html",
        //     "img": "https://placehold.co/600x400/d8c677/31343C",
        //     "kind": "",
        // },
        // {
        //     "name": "Proyecto 4",
        //     "description": "EL CUATROOOO",
        //     "link": "/project4.html",
        //     "img": "https://placehold.co/600x400/34f888/31343C",
        //     "kind": "big",
        // },
        // {
        //     "name": "Proyecto 5",
        //     "description": "el quinto jeje",
        //     "link": "/project5.html",
        //     "img": "https://placehold.co/600x400/83c412/31343C",
        //     "kind": "",
        // },
        // {
        //     "name": "Proyecto 6",
        //     "description": "este es el sexto!!",
        //     "link": "/project6.html",
        //     "img": "https://placehold.co/600x400/123456/31343C",
        //     "kind": "",
        // },
    ],
};

export default projects;